lang: es-MX
format:
  latex: false
  html:
    title: iteraciones
    tagline: escribir, compartir, re-existir
    logo: ""
    base-url: ""
    theme: dark
    accent: lime
    generate: true
  pdf:
    generate: false
    toc: false
    show-date: false
  epub:
    generate: false
  markdown:
    generate: false

